name: Build Hugo to gh-pages Branch
on:
  push:
    branches: [master, dev]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.81.0'
          extended: true

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      
      - name: Checkout Documentation Repo (dev)
        uses: actions/checkout@v3
        with:
          ref: dev
          path: docs

      - name: Checkout DefectDojo Repo (dev)
        uses: actions/checkout@v3
        with:
          repository: DefectDojo/django-DefectDojo
          submodules: recursive  # Fetch the Docsy theme
          ref: dev
          path: dojo

      - run: ls -al

      - run: cp -r ./docs/proprietary_plugins ./dojo/docs/content/en/ | true
      - run: cp -r ./docs/proprietary_images/* ./dojo/docs/static/images/ | true
      - run: cp -r ./docs/layout/partials/* ./dojo/docs/layout/partials/ | true
      - run: cp -r ./docs/js ./dojo/docs/static/ | true
      - run: ./docs/hotfix.bash | true
      - run: cp ./docs/config.dev.toml ./dojo/docs/
      - run: cd dojo/docs && npm ci
      - run: cd dojo/docs && hugo --minify --config config.dev.toml
      - run: ls -l ./dojo/docs/public/*

      # for dev we move everything into a subfolder, so the master version stays in the root
      - run: mkdir /tmp/dev && mv dojo/docs/public/* /tmp/dev/

      - name: Checkout Documentation Repo (master)
        uses: actions/checkout@v3
        with:
          ref: master
          path: docs

      - name: Checkout DefectDojo Repo (master)
        uses: actions/checkout@v3
        with:
          repository: DefectDojo/django-DefectDojo
          submodules: recursive  # Fetch the Docsy theme
          ref: master
          path: dojo

      - run: rm -rf ./dojo/docs/content/en/proprietary_plugins 
      - run: cp -r ./docs/proprietary_plugins ./dojo/docs/content/en/ | true
      - run: cp -r ./docs/proprietary_images/* ./dojo/docs/static/images/ | true
      - run: cp -r ./docs/layout/partials/* ./dojo/docs/layout/partials/ | true
      - run: cp -r ./docs/js ./dojo/docs/static/ | true
      - run: ./docs/hotfix.bash | true
      - run: cp ./docs/config.master.toml ./dojo/docs/
      - run: cd dojo/docs && npm ci
      - run: cd dojo/docs && hugo --minify --config config.master.toml
      - run: mv /tmp/dev dojo/docs/public/
      - run: ls -l ./dojo/docs/public/*

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with: # publishes to the `gh-pages` branch by default
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dojo/docs/public
          cname: documentation.defectdojo.com
