name: Build Hugo to gh-pages Branch
on:
  push:
    branches: [master, dev]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.81.0'
          extended: true

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      
      - name: Checkout Documentation Repo
        uses: actions/checkout@v3
        with:
          ref: master

      - name: Checkout tools repo
        uses: actions/checkout@v3
        with:
          repository: DefectDojo/django-DefectDojo
          path: docs
          ref: dev

      - run: cp -r ./proprietary_plugins ./docs/content/en/ | true
      - run: cp ./proprietary_images/* ./docs/static/images/ | true
      - run: ./hotfix.bash | true
      - run: cp ./config.dev.toml ./docs/
      - run: cd docs && npm ci
      - run: cd docs && hugo --minify --config config.dev.toml
      - run: ls -l ./docs/public/*

      # for dev we move everything into a subfolder, so the master version stays in the root
      - run: mkdir /tmp/dev && mv docs/public/* /tmp/dev/

      - name: Checkout tools repo
        uses: actions/checkout@v3
        with:
          repository: DefectDojo/django-DefectDojo
          path: docs
          ref: master

      - run: rm -rf ./docs/content/en/proprietary_plugins 
      - run: cp -r ./proprietary_plugins ./docs/content/en/ | true
      - run: cp ./proprietary_images/* ./docs/static/images/ | true
      - run: ./hotfix.bash | true
      - run: cp ./config.master.toml ./docs/
      - run: cd docs && npm ci
      - run: cd docs && hugo --minify --config config.master.toml
      - run: mv /tmp/dev docs/public/
      - run: ls -l ./docs/public/*

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with: # publishes to the `gh-pages` branch by default
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/public
          cname: documentation.defectdojo.com
